[package]
name = "cleanbox"
version = "0.1.0"
edition = "2024"

[dependencies]
rexif = "0.7.5"
clap = { version = "4.5.41", features = ["derive"] }
sha1 = "0.10"
strsim = "0.11"
infer = "0.16"
regex = "1.10"
chrono = "0.4"
lazy_static = "1.4"
rustyline = "14.0"

[dev-dependencies]
tempfile = "3.8"
